create procedure PromoteStudents @STUDY NVARCHAR(100), @SEMESTER INT
AS
BEGIN
	BEGIN TRANSACTION
	DECLARE @IDSTUDY INT = (SELECT IDSTUDY FROM STUDIES WHERE NAME = @STUDY)

	IF @IDSTUDY IS NULL
	BEGIN
		SET @BLAD = "Nie ma takich studiów";
		RAISERROR(@BLAD, 16, 1);
		RETURN;
	END;
	
	DECLARE @IDENROLLMENT INT = (SELECT IDENROLLMENT FROM ENROLLMENT E, STUDIES S WHERE E.IDSTUDY = S.IDSTUDY AND S.NAME = @STUDIES AND SEMESTER = (@SEMESTER + 1));
	IF @IDENROLLMENT IS NULL
	BEGIN
		INSERT INTO ENROLLMENT (IDENROLLMENT, SEMESTER, IDSTUDY, STARTDATE) VALUES ('30', (@SEMESTER + 1), @IDSTUDY, GETDATE());
	END;

	UPDATE STUDENT SET IDENROLLMENT = @IDENROLLMENT;
	COMMIT
END;